### ISSUE TITLE
Personagens que irão interagir com o jogador

### ISSUE THREAD

**Issue by Leomaxson** [EngSoft-Grupo2/gatopreto#17]
Definir os personagens que representarão a "Corte" do Reign. No caso, esses personagens serão os que vão levantar as situações onde o jogador deverá fazer uma escolha.

**Comment by Leomaxson** [comment]
Personagens:

- Dono da Empresa: É o dono da empresa de software que o jogador está inserido.
- Cliente: O cliente que encomendou o desenvolvimento do software em questão.
- RH: Pessoa responsável pelo gerenciamento dos recursos humanos da empresa.
- Programador: 
- Alguém relacionado ao banco de dados
- Designer de interface
- Tester

**Comment by Leomaxson** [comment]
Deverão ser dois personagens programadores. Programador1 e Programador2. Eles terão cartas individuais e funcionarão como par de programação caso o jogador tenha escolhido uma metodologia de programação em pares para o projeto.

**Comment by Leomaxson** [comment]
Definir se o personagem do Cliente será o cliente de fato ou um representante dele.

**Comment by Leomaxson** [comment]
Tem que ter também a figura do Arquiteto de Software.

**Comment by Gabrieldr** [comment]
![carta7_office](https://user-images.githubusercontent.com/8468861/33103198-176821f8-cf08-11e7-99f6-3f57da1957a9.png)
![carta6_office](https://user-images.githubusercontent.com/8468861/33103199-179d14da-cf08-11e7-847b-ed2bcde1cfbc.png)
![carta4_office](https://user-images.githubusercontent.com/8468861/33103201-17cad6fe-cf08-11e7-8426-ecf9e8179724.png)
![carta5_office](https://user-images.githubusercontent.com/8468861/33103203-17f75bac-cf08-11e7-9cec-24389f3f483b.png)
![carta3_office](https://user-images.githubusercontent.com/8468861/33103204-181cfee8-cf08-11e7-94fa-127bd78046a9.png)
![carta2_office](https://user-images.githubusercontent.com/8468861/33103205-1844617c-cf08-11e7-8bb5-732b5e02c5e2.png)
![carta1_office](https://user-images.githubusercontent.com/8468861/33103206-1872760c-cf08-11e7-95e3-b346eff1cefd.png)
