### ISSUE TITLE
Criar um logotipo para a empresa

### ISSUE THREAD

**Issue by brunocpf** [EngSoft-Grupo2/gatopreto#2]
- Criar um logotipo para a empresa, formato livre

**Comment by Gabrieldr** [comment]
Algumas sugestões de logo pro jogo. Na minha opinião a primeira é bem legal

![01](https://user-images.githubusercontent.com/8468861/30570841-349b1e22-9cba-11e7-91a7-703cfdc6dd0a.jpg)
![02](https://user-images.githubusercontent.com/8468861/30570843-34a0deca-9cba-11e7-9d81-23c8710bf5c6.jpg)
![03](https://user-images.githubusercontent.com/8468861/30570842-34a0c020-9cba-11e7-9bed-fba2c83680c0.jpg)
![04](https://user-images.githubusercontent.com/8468861/30570844-34a67dd0-9cba-11e7-8ee9-160ad8a4ad8f.jpg)

**Comment by brunocpf** [comment]
Já feito, ver apresentações no Google Drive.
