### ISSUE TITLE
Modelo de dados da Carta

### ISSUE THREAD

**Issue by Leomaxson** [EngSoft-Grupo2/gatopreto#22]
Criar o modelo dos dados que terão que ser armazenados para uma carta do jogo.

**Comment by Leomaxson** [comment]
- ID (Integer)
- - ID da carta.
- Tipo (Enum: Tipo)
- - Tipo da carta para diferenciar quais cartas deverão entrar no deck desde o início do jogo.
- - Além disso, serve para agrupar tipos de cartas semelhantes que entrarão no deck quando o jogador tomar uma escolha específica em uma carta X.
- Personagem (Tipo: Personagem)
- - Personagem do jogo que está originando a carta e que vai interagir com o usuário naquele contexto.
- Descrição (String)
- - Descrição da situação que a carta apresenta para o usuário tomar uma decisão.
- Decisao Direita (String)
- - Descrição da decisão que o usuário tomará quando deslizar a carta para a direita.
- Decisao Esquerda (String)
- - Descrição da decisão que o usuário tomará quando deslizar a carta para a esquerda.
- Atributos Direita (array<int>)
- - Mudanças nos atributos se o usuário tomar a decisão da direita.
- Atributos Esquerda (array<int>)
- - Mudanças nos atributos se o usuário tomar a decisão da esquerda.
- Ajuda da Carta (string)
- - Ajuda da carta que explica o conceito por trás da decisão que o usuário terá que tomar naquela carta.

**Comment by brunocpf** [comment]
Vou considerar isso fechado, já que eu já fiz uma implementação baseada nisso. Qualquer sugestão de mudança, é só abrir de novo.
