### ISSUE TITLE
Definir conjunto de imagens para os personagens do jogo

### ISSUE THREAD

**Issue by Gabrieldr** [EngSoft-Grupo2/gatopreto#25]

**Comment by Gabrieldr** [comment]
Pessoal, esse conjunto de avatares seria adequado para o nosso jogo?

Tenho uma versão em formato de vetor deles.

![of166l0](https://user-images.githubusercontent.com/8468861/31918547-f5efc7ca-b83b-11e7-9119-b8481c5ef35f.jpg)

**Comment by brunocpf** [comment]
Boa! Vou fechar.
