### ISSUE TITLE
Preparo da apresentação final

### ISSUE THREAD

**Issue by brunocpf** [EngSoft-Grupo2/gatopreto#28]
Preparar a apresentação final.

Lembre-se de se alocar clicando no botão Asignees ao lado e mudar a issue para "In Progress" na aba Projects quando começar a fazer!

**Comment by Allan045** [comment]
Olá! Estou deixando essa mensagem para sinalizar que venho acompanhando o trabalho do seu grupo.
Talvez essa não seja a issue mais adequada para isso, espero que não atrapalhe.
 
Tenho duas sugestões:
1- Criar uma pasta na raiz do projeto, para mostrar os documentos de requisitos, arquitetura, etc.
2- Deixar claro o funcionamento do aplicativo, talvez um vídeo mostrando o uso do app.

Abraços,
Allan.
