### ISSUE TITLE
Definir atributos

### ISSUE THREAD

**Issue by brunocpf** [EngSoft-Grupo2/gatopreto#5]
- Definir no mínimo 3 atributos.

**Comment by Leomaxson** [comment]
Atributos que estão definidos no momento:
* Dinheiro (orçamento do projeto)
* Pessoal (representa aspectos relacionados a sua equipe de trabalho, número de empregados, felicidade da equipe, qualificação dos profissionais, etc)
* Qualidade (Representa a qualidade do software que está sendo desenvolvido).
* Cliente (Representa aspectos relacionados ao cliente em si, como satisfação, nível de engajamento, etc)

Duas possibilidades para o término do jogo:
- Máximo/Mínimo de um atributo
- Terminar o "tamanho" do deck.

Términos possíveis para o caso de Max/Min dos atributos:
- Max Dinheiro: ----
- Min Dinheiro: Você esgotou a verba para a execução do projeto. Não será possível concluir para o cliente.
- Max Pessoal: A equipe de desenvolvimento está tão qualificada que ficou muito caro manter.
- Min Pessoal: O grupo de trabalho ficou muito desorganizado, a equipe não tem mais confiança para continuar no projeto. Alguns funcionários abandonaram o projeto.
- Max Qualidade: O código do software ficou muito complexo e exagerado além dos requisitos. Manter esse padrão de qualidade deixa o desenvolvimento muito engessado.
- Min Qualidade: O código apresenta muitos bugs e é de difícil manutenção. O caráter caótico impede o desenvolvimento de continuar.
- Max Cliente:  -----
- Min Cliente: O cliente está insatisfeito com o andamento do produto é cancelou o desenvolvimento do projeto.

No caso de término por causa do fim do deck, o valor dos atributos e as escolhas serão analisadas para gerar um final condizente para o jogador.

**Comment by ramirocosta** [comment]
Max Dinheiro: O dinheiro para o projeto não foi empregado como deveria, a verba ficou retida muito tempo e seu chefe percebeu. Sob investigação interna, você foi afastado do projeto.
Min Dinheiro: Você esgotou a verba para a execução do projeto. Não será possível concluir o projeto.
Max Pessoal: A equipe de desenvolvimento está tão grande e qualificada que ficou muito caro manter-la. Rendendo pouco e exigindo muito, sua equipe se desentende e o projeto é suspenso.
Min Pessoal: O grupo de trabalho ficou muito desorganizado, a equipe não tem mais confiança para continuar no projeto. Alguns funcionários abandonaram o projeto, com isso o time é desfeito e você é remanejado.
Max Qualidade: O código do software ficou muito complexo e exagerado além dos requisitos. Manter esse padrão de qualidade deixa o desenvolvimento muito engessado. O cliente não pode arcar com manutenção e resolve transferir o desenvolvimento para outra empresa.
Min Qualidade: O código apresenta muitos bugs e é de difícil manutenção. O caráter caótico impede o desenvolvimento de continuar.
Max Cliente: O cliente se empolga, porem sua visão não condiz com a realidade. Sua participação intrusiva e exigente torna o projeto tão caro que ele é obrigado a suspender o desenvolvimento.
Min Cliente: O cliente está insatisfeito com o andamento do produto é cancelou o desenvolvimento do projeto.
